spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5442/webnovel}
    username: ${DB_USERNAME:webnovel}
    password: ${DB_PASSWORD:webnovel}
  jpa:
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
